name: Build on push
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: wildbit/dotnet-builder
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Show .net version
      run: dotnet --version
    - name: Build the project
      run: |
        printenv
        msbuild
